### ISSUE TITLE
zip2exe multiple issues

### ISSUE THREAD

**Issue by LotharSoens** [bitwiseworks/zip-os2#1]
zip2exe.cmd (of unzip-6.0-7.oc00) has some minor flaws:
(1) produces uppercase *exe names only
(2) annoying "40298 extra bytes ..."
(3) *zip filenames with inner blanks not accepted 
Always reproducible, typical example attached.
[zip2exe_ticket.txt](https://github.com/bitwiseworks/zip-os2/files/4703989/zip2exe_ticket.txt)

**Comment by SilvanScherrer** [comment]
Case 1 and 3 are issues which can be fixed easily.

Case 2 is not a issue at all. The man page has to say this:

     Note that self-extracting archives made with unzipsfx are no
     more  (or  less) portable across different operating systems
     than is the unzip executable itself.   In  general  a  self-
     extracting  archive  made  on  a particular Unix system, for
     example, will only self-extract under  the  same  flavor  of
     Unix.  Regular unzip may still be used to extract the embed-
     ded archive as with any normal  zipfile,  although  it  will
     generate  a harmless warning about extra bytes at the begin-
     ning of the zipfile.

**Comment by SilvanScherrer** [comment]
All fixed in the latest unzip rpm. Thd rpm is in exp repo now.
